### ISSUE TITLE
可以考虑增加equuleus分支

### ISSUE THREAD

**Issue by jack9603301** [zengkid/build-vyos-lts#3]
VyOS 1.3 进入特性软冻结，发行代号是equuleus，详见：

https://github.com/jack9603301/build-vyos-lts

**Comment by zengkid** [comment]
done

**Comment by jack9603301** [comment]
@zengkid 为什么不考虑增加分支？和vyos的分支模型对应

**Comment by jack9603301** [comment]
还有，滚动版本目前是1.4

**Comment by zengkid** [comment]
有分支的。master就是1.3，crux是1.2。
