### ISSUE TITLE
编译设置有误

### ISSUE THREAD

**Issue by jack9603301** [zengkid/build-vyos-lts#5]
1. 为什么不设置`equuleus`分支
2. `vyos-build`的分支和`docker`的`tag`为`equuleus`，`current`分支版本是1.4
3. 其他问题请联系我的qq

**Comment by zengkid** [comment]
文档是这么描述的，current不是1.3吗？默认branches也是current，以前1.2默认是crux。
For VyOS 1.3 (equuleus, current)
$ git clone -b current --single-branch https://github.com/vyos/vyos-build

**Comment by jack9603301** [comment]
1.3 刚刚冻结，文档可能还没有更新

请以`vyos-build`的github repo的分支模型为准，1.3刚刚进入特性冻结，创建了新的分支`equuleus`，`current`为1.4

**Comment by zengkid** [comment]
noted
